apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: ghp-web-app-frontend
  namespace: greenhouse
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ghp-web-app-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ghp-web-app-frontend
    spec:
      containers:
        - name: ghp-web-app-frontend
          image: us-central1-docker.pkg.dev/snappy-lattice-443619-v7/greenhouse-container-registry/ghp-web-app-frontend:V0.00.01
          imagePullPolicy: Always
          ports:
            - containerPort: 9191
              protocol: TCP
          resources:
            requests:
              memory: "500Mi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: TZ
              value: "Asia/Colombo"
      imagePullSecrets:
        - name: artifact-registry-secret
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: false
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 120
